In [13]:
import numpy as np

print('Versão do Numpy:', np.version.version)


Versão do Numpy: 2.2.4


# Manipulação em linha e colunas

In [14]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 1, 2, 3, 4, 5]])

print(a)
print('Shepe do meu Array 2D', a.shape)

[[1 2 3 4 5 6 7]
 [8 9 1 2 3 4 5]]
Shepe do meu Array 2D (2, 7)


# Para pega um item especifico, uftilizamos a notação [linha, coluna]



In [15]:
a [0, 3]

np.int64(4)

# Para pega a segunda linha, por exemplo:


In [16]:
a [1]

array([8, 9, 1, 2, 3, 4, 5])

# Notação negativa


In [17]:
a[1, -1]

np.int64(5)

# Pegar uma coluna especifica

In [18]:
print(a)



a[:,2]

[[1 2 3 4 5 6 7]
 [8 9 1 2 3 4 5]]


array([3, 1])

# Metodo de slicing, de lista, tembem funciona d oarray

## [start_index:end_index] -> step não é obrigatorio
## // caso não queiamos adicionar o end index, é so colocar:

In [19]:
print(a)

a[0, 1:]

[[1 2 3 4 5 6 7]
 [8 9 1 2 3 4 5]]


array([2, 3, 4, 5, 6, 7])

In [20]:
a[0 ,1::2]

array([2, 4, 6])

# Desfios

Atividade : Array Numpy 1d, 2d, shape e fatiamento
  
### 1. Array 1D

 a) Crie um Array numpy chado `vetor` com números de  10 de 50 em 10

 b) Imprima o array

 c) Inprima o tamanho (shape) desse array

 d) Imprima apemas os 3 primeros elementos usando slicing

 e) Imprima os dois elementos usando slicing


In [21]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])

print('')
print(array)
print('')

print('O shape é',array.shape)
print('')

print('Os dos tris é:',array[:3])
print('')

print('Os dois é:',array[3:])
print('')


[10 20 30 40 50]

O shape é (5,)

Os dos tris é: [10 20 30]

Os dois é: [40 50]



# 2 Array 2D

a) Crie um array chamado `matris` com duas linhas : a primera `[1, 2, 3]` e a segunda `[4, 5, 6]`

b) Imprma o array

c) Imprima o tamanho (shae) da matriz

d) Imprima apenas a segunda linha da matriz

e) Imprima apenas o elemento da primara linha e a terceira coluna

In [40]:


matris = np.array([[1, 2, 3],[4, 5, 6]])

print(matris)
print('')

print(matris.shape)
print()

print(matris[1, :])
print()

print(matris[0, -1])
print()





[[1 2 3]
 [4 5 6]]

(2, 3)

[4 5 6]

3

